### model
# Use the base model you originally used (local folder with config.json + model.safetensors)
model_name_or_path: /media/seonho/34B6BDA8B6BD6ACE/AAAI/project/Drive/LLaMA-Factory/Qwen2-VL-2B-Instruct_tok168064_resized
trust_remote_code: true
image_resolution: 524288
video_resolution: 16384
resize_vocab: false


enable_liger_kernel: true
use_unsloth_gc: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
adapter_name_or_path: /media/seonho/34B6BDA8B6BD6ACE/AAAI/project/Drive/LLaMA-Factory/saves/qwen2_vl-2b/pretrain_clean
freeze_vision_tower: true
freeze_multi_modal_projector: true
train_mm_proj_only: false

# DeepSpeed (memory efficient)
deepspeed: /media/seonho/34B6BDA8B6BD6ACE/AAAI/project/Drive/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

# LoRA targets for Qwen2-VL
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj

### dataset
dataset: train_ft2_cot_tot_motion
template: qwen2_vl
cutoff_len: 2048
max_new_tokens: 512
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_vl-2b/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
gradient_checkpointing: true

learning_rate: 1.0e-4
num_train_epochs: 12.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

temperature: 0.1
top_p: 0.1
top_k: 10
skip_special_tokens: false